#From nvcr.io/partners/gridai/pytorch-lightning:v1.3.8
#From nvidia/cuda:11.1-devel-ubuntu20.04
From nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04

# ロケール設定
#RUN apt-get update \
#  && apt install -y tzdata \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*

#ENV TZ Asia/Tokyo
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Hack to not have tzdata cmdline config during build
RUN ln -fs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# REF: https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile
RUN apt-get update -q && \
  apt-get install -q -y --no-install-recommends \
  build-essential \
  bzip2 \
  ca-certificates \
  git \
  # OpenCV の動作に必要
  libgl1-mesa-dev \
  libglib2.0-0 \
  # Ubuntu 版 PCL install
  libpcl-dev \
  libsm6 \
  libxext6 \
  libxrender1 \
  mercurial \
  openssh-client \
  procps \
  subversion \
  wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# <<< Miniconda3 install <<<

ENV PATH /opt/conda/bin:$PATH

CMD [ "/bin/bash" ]

# Leave these args here to better use the Docker build cache
ARG CONDA_VERSION=py38_4.10.3
ARG SHA256SUM=935d72deb16e42739d69644977290395561b7a6db059b316958d97939e9bdf3d

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh -q && \
  echo "${SHA256SUM} miniconda.sh" > shasum && \
  if [ "${CONDA_VERSION}" != "latest" ]; then sha256sum --check --status shasum; fi && \
  mkdir -p /opt && \
  sh miniconda.sh -b -p /opt/conda && \
  rm miniconda.sh shasum && \
  ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
  echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
  echo "conda activate base" >> ~/.bashrc && \
  find /opt/conda/ -follow -type f -name '*.a' -delete && \
  find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
  /opt/conda/bin/conda clean -afy

# <<< conda initialize <<<
RUN echo 'export LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64:${LD_LIBRARY_PATH}' >> ~/.bashrc \
  && echo 'export CUDA_HOME=/usr/local/cuda-11.1' >> ~/.bashrc
#export LD_LIBRARY_PATH = "/usr/local/cuda-11.1/lib64:$LD_LIBRARY_PATH"
#export CUDA_HOME="/usr/local/cuda-11.1"

# <<< pclpy install <<<
# REF: https://github.com/davidcaron/pclpy
RUN conda config --add channels conda-forge
RUN conda config --add channels davidcaron
RUN conda install -y pclpy

# realsense の python ラッパーのインストール
# REF: https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python#installation
RUN pip install pyrealsense2

# PyTorch のインストール
RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

# その他必要パッケージのインストール
WORKDIR /home
ADD requirements.txt /home
RUN pip install -r ./requirements.txt

#ENV PATH $PATH:/opt/conda/envs/env/bin:/opt/conda/bin

#CMD ["/bin/bash"]