FROM alpine

RUN apk update \
 && apk --no-cache add \
 	python3 \
 	py3-pip \
 	py3-numpy
 	build-base \
 	python3-dev \
 	py3-matplotlib \
 && pip3 install --upgrade pip \
 && pip3 install jupyter \

EXPOSE 8888

ENTRYPOINT [ "jupyter" ]
CMD [ "notebook", "--ip=*", "--no-browser", "--allow-root" ]